[book]
authors = ["explosion-mental"]
language = "en"
src = "docs/"
title = "Wallust Guide"

[output.html]
git-repository-url = "https://codeberg.org/explosion-mental/wallust"
git-repository-icon = "fab-square-git"
default-theme = "dark"
