[package]
name = "wallust"
# name = "wal" # TODO drop in replacement for wal
version = "2.4.1"
edition = "2021"
license = "MIT"
authors = [ "explosion-mental" ]
keywords = [ "cli" ]
categories = [ "command-line-utilities" ]
description = "Generate a 16 color scheme based on an image."
repository = "https://codeberg.org/explosion-mental/wallust"
homepage = "https://codeberg.org/explosion-mental/wallust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
image = "0.24"
lab = "0.11"
owo-colors = "3.5"
toml = "0.7"
serde_json = "1.0"
shellexpand = "3.1"
glob = "0.3"
new_string_template = "1.4"
spinners = "4.1"
dirs = "5.0"
itertools = "0.11"

clap  = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
