# -- global space -- #

# How to parse the image:
# * full - reads the whole image (more precision)
# * resized - resizes the image before parsing it (more color mixing, faster)
# * wal - uses image magick `convert` to read the image
backend = "full"

# What color space to use to produce and select the most prominent colors:
# * lab - use CIEL*a*b color space
# * labmixed - variant of lab that mixes colors, unless there are not enough colors (fallbacking to lab usual behaviour)
color_space = "lab"

# Difference between similar colors, used by the colorspace:
#  <= 1       Not perceptible by human eyes.
#  1 - 2      Perceptible through close observation.
#  2 - 10     Perceptible at a glance.
#  11 - 49    Colors are more similar than opposite
#  100        Colors are exact opposite
threshold = 11

# Use the most prominent colors in a way that makes sense, a scheme:
# * dark    - 8 dark colors, color0 darkest - color7 lightest
# * dark16  - same as dark but it displays 16 colors
# * light   - 8 light colors, color0 lightest - color7 darkest
# * light16 - same as light but displays 16 colors
filter = "dark"

# -- entries are just a config file you wish to apply `wallust` generated colors to -- #
[[entry]]
# a relative path to a file where wallust.toml is (~/.config/wallust/)
template = "dunstrc"

# absolute path to the file to write the template (after templating)
target = "~/.config/dunst/dunstrc"

[[entry]]
template = "zathurarc"
target = "~/.config/zathura/zathurarc"

[[entry]]
template = "bars.glsl"
target = "~/.config/glava/bars.glsl"
