# global space #

# possible values:
#  * full - reads the whole image
#  * resized - resizes the image before parsing it
parser = "resized"

[[entry]] # An entry is just a config file you wish to apply `wallust` generated colors
# a relative path to a file where wallust.toml is (~/.config/wallust/)
template = "dunstrc"
# absolute path to the file to write the template (after templating)
path = "~/.config/dunst/dunstrc"

[[entry]]
template = "zathurarc"
path = "~/.config/zathura/zathurarc"

[[entry]]
template = "bars.glsl"
path = "~/.config/glava/bars.glsl"
