when:
  - path: 'src/*'
  - event: pull_request
  - event: push
    branch: [ dev, master ]


steps:
  cargo_check:
    image: rust:1.79
    # A simple check ensures a compilation
    # XXX While there could have been a clippy here,
    #     my main concern is whether it builds or not.
    commands:
    - cargo check --all-targets
