variables:
  - &doc_files [ 'docs/*', 'book.toml', 'README.md', 'tests/docs.rs', 'woodpecker/*' ]

when:
  branch: master
  event: [ push, pull_request ]
  path:
    include: *doc_files

clone:
  git:
    image: woodpeckerci/plugin-git

# Generate tables -> build -> publish
steps:
  generate-tables:
    image: rust:latest
    commands:
    - cargo test --quiet --features=doc,iter --test=docs
    when:
      event: [pull_request, push]
      path:
        include: *doc_files

  build:
    image: peaceiris/mdbook:latest
    commands:
      - mdbook build
    when:
      event: [pull_request, push]
      path:
        include: *doc_files

  publish:
    image: bitnami/git
    depends_on: [ build ]
    environment:
      berg_pat:
        from_secret: berg_pat
    commands:
      - set -eu # non-zero exit
      - export MDBOOK_OUTPUT=book
      - export TMP_DIR=tmp-pages
      - rm -rf "$TMP_DIR"
      - git clone -b pages "https://${berg_pat}@codeberg.org/${CI_REPO}.git" "$TMP_DIR"
      # Replace site contents while keeping the pages branch history
      - rm -rf "$TMP_DIR"/*
      - cp -a "$MDBOOK_OUTPUT"/. "$TMP_DIR"/
      - cd "$TMP_DIR"
      - git config user.email "woodpecker@codeberg.org"
      - git config user.name "Woodpecker CI"
      - git add -A
      - git diff --cached --quiet && echo "No changes to publish" && exit 0
      - git commit -m "Woodpecker CI ${CI_BUILD_CREATED}"
      - git push
    when:
      event: push
      path:
        include: *doc_files
