# when:
#   - event: [ push, pull_request ]
#     path: 'docs/*'

when:
  branch: master
  event: push
  path:
    include: [ 'docs/*', 'book.toml', 'README.md', 'tests/docs.rs' ]

clone:
  git:
    image: woodpeckerci/plugin-git

# Generate tables -> build -> publish
steps:
  generate-tables:
    image: rust:latest
    commands:
    - cargo test --quiet --features=doc,iter --test=docs
    when:
      - event: [pull_request, push]
        path:
          include: [ 'docs/*', 'book.toml', 'README.md', 'tests/docs.rs' ]
  build:
    image: peaceiris/mdbook:latest
    commands:
      - mdbook build
    when:
      - event: [pull_request, push]
        path:
          include: [ 'docs/*', 'book.toml', 'README.md', 'tests/docs.rs' ]

  publish:
    image: bitnami/git
    secrets: [ berg_pat ]
    environment:
      - MDBOOK_OUTPUT=book
    commands:
      - git config --global user.email "woodpecker@codeberg.org"
      - git config --global user.name "Woodpecker CI"
      - git clone -b pages https://$berg_pat@codeberg.org/$CI_REPO.git $CI_REPO_NAME
      - cp -ar $MDBOOK_OUTPUT $CI_REPO_NAME/
      - cp .domains $CI_REPO_NAME || true
      - cd $CI_REPO_NAME
      - git add .
      - git commit -m "Woodpecker CI ${CI_BUILD_CREATED}"
      - git push
    when:
      - event: push
        path:
          include: [ 'docs/*', 'book.toml', 'README.md', 'tests/docs.rs' ]
